Tests/Data/regionInfo-Nuremberg.json, Tests/Data/regionInfo-Sydney.json, Tests/Data/regionInfo-Vancouver.json, Tests/Data/regionInfo-multi.json, Tests/parsing/TKBuzzInfoProviderTest.swift, TripKit.xcodeproj/project.pbxproj, TripKit/Classes/core/ServerKit/SVKTransportModes.h, TripKit/Classes/core/ServerKit/SVKTransportModes.m, TripKit/Classes/model/API/RegionAPIModel.swift
`TKBuzzInfoProvider.fetchRegionInformation` now returns a bunch more information about transport modes.
In particular `API.RegionInfo.modes` got added which has all the information. Call `regionInfo.specificDetails(for: ...)` to get information for a single mode.
Note that there's also a `lockedModes` array in there with information about transport modes which you first need to unlock in your 3scale developer settings.
=> Feature/new regionInfo.json content

TripKitUI/core/TransportKitUI/SGTripSegmentsView.h, TripKitUI/core/TransportKitUI/SGTripSegmentsView.m, TripKitUI/core/TransportKitUI/SGTripSummaryCell.h, TripKitUI/core/TransportKitUI/SGTripSummaryCell.swift
This PR focuses on exposing an entry point for `SGTripSegmentView` to configure optional coloring of public transport modes.
=> allow optional transit color coding in segment view

TripKit.xcodeproj/project.pbxproj, TripKit/Classes/Loc+TripKit.swift, TripKit/Classes/model/CoreData/SegmentTemplate.h, TripKit/Classes/model/CoreData/SegmentTemplate.m, TripKit/Classes/model/CoreData/Shape+CoreDataClass.swift, TripKit/Classes/model/CoreData/Shape+CoreDataProperties.swift, TripKit/Classes/model/TKPathFriendliness.swift, TripKit/Classes/server/TKParserHelper.m, TripKit/Classes/server/TKRoutingParser.m, TripKitModel.xcdatamodeld/6-SegmentRealTimeVehicle.xcdatamodel/contents, TripKitUI/views/TKPathFriendlinessView.swift, TripKitUI/views/TKPathFriendlinessView.xib
- Added `TKPathFriendliness` enum, which now includes "dismount"
- Updated `TKPathFriendlinessView` to also include "dismount" section where appropriate
- Adjusts path colouring and dash pattern according to friendliness
Related API PR: https://github.com/skedgo/tripgo-api/pull/90
=> Preparing for "hop" and "dismount" shapes

Sources/TripKitUI/cards/TKUIRoutingResultsCard+Errors.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/views/TKUITripBoyView.swift
This addresses the issue that when an error view is presented in the `TKUIRoutingResultsCard`, tapping on the Transport button appears to do nothing, i.e., the mode picker does not appear.
=> Make sure mode picker is visible above error view

Sources/TripKitUI/cards/TKUIHomeCard.swift
- Set map toolbar buttons on initialisation
- Restore card dragging when selecting a city
- First move card, then zoom to a city, to make sure it's using the correct padding
=> Home card fixes

Sources/TripKit/model/CoreData/TripRequest+CoreDataClass.swift
As discussed, when both from and to are in the same region, don't use interregional when one of them falls in the overlap of two regions.
=> Don't use interregional when from and to are in the same region

Sources/TripKit/model/API/ShareCarAPIModel.swift
This issue was identified when testing the new GoGet realtime API. The dates in `BookingAvailability` weren't marked with the new property wrapper, which caused the decoding to fail.
=> Date should be treated as either ISO or 1970

Sources/TripKitUI/views/results/TKUIResultsTitleView.xib
Previously, the constraint was set from the "To" label to the "Close" button. This means occasionally, the "From" text will extend way beyond the edge of the view.
=> Constraint both From and To label so both don't overflow

Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+ToggleModes.swift
Addressing this ticket: https://redmine.buzzhives.com/issues/15535.
**Steps to reproduce.**
1. Plan a trip, open the transport selector by tapping "Transport"
2. Try to disable a mode that is currently enabled.
3. Close the transport mode selector, and open it again.
**Expected behaviour**
The mode remains disabled
**Actual behaviour**
The mode is still enabled
=> Persist change in transport mode selection in routing results card

Sources/TripKit/model/TKSegment.swift
... as nuking them can crash the app if they were added to the map.
=> Don't add DLSEntry's to the map

Sources/TripKit/model/TKBookingTypes.swift
We have made a few changes to the `Confirmation.Purchase` JSON:
1. `validFromTimestamp` (ISO 8601) replacing `validFrom` and `timezone`
2. `paymentTimestamp` in the future, will not appear for now
=> working with changes in purchase json

Sources/TripKitUI/views/TKUIAutocompletionResultCell.swift
This is first reported in this ticket: https://redmine.buzzhives.com/issues/15589
Symptom: As the table view animates the autocompletion results, some cells appear to go on top of the other.
=> Fixed ghosting in autocomplete cell

Sources/TripKit/helpers/TKRegionOverlayHelper.swift, Sources/TripKit/managers/TKRegionManager.swift, Sources/TripKit/vendor/ASPolygonKit/CLLocationCoordinate2D+EncodePolylineString.swift, Sources/TripKit/vendor/ASPolygonKit/Geometry.swift, Sources/TripKit/vendor/ASPolygonKit/MKPolygon+Union.swift, Sources/TripKit/vendor/ASPolygonKit/Polygon.swift, Tests/TripKitTests/polygon/ASPolygonKitTests.swift, Tests/TripKitTests/polygon/data/polygons-au-211102.json, TripKit.xcodeproj/project.pbxproj
1. Allow intersections that are right on a polygon corner
2. Increase precision of point equality checks
3. Make sure polygons are clockwise before unifying
Also: Refactoring, debugging help, turning polygons into encoded polylines and more details for tests
=> Polygon union fixes

Sources/TripKitUI/views/results/TKUISheet.swift, Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
1. Time picker order is now: now/leave at/leaver after, then the
time picker, and then "Done", rather than "Done" being in the middle
2. Temporary make all elements behind the overlay non accessible while
the sheet is being displayed.
Addresses RM16034
=> Improve VoiceOver support for time picker and sheet

Sources/TripKit/core/Loc+TripKitUI.swift, Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel+State.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel.swift, Sources/TripKitUI/views/TKUITripSegmentsView.swift, Sources/TripKitUI/views/results/TKUIResultsTitleView.swift, Sources/TripKitUI/views/results/TKUIResultsTitleView.xib, Sources/TripKitUI/views/results/TKUIRoutingQueryInputTitleView.swift, Sources/TripKitUI/views/results/TKUIRoutingQueryInputTitleView.xib, Sources/TripKitUI/views/results/TKUITimePickerSheet.swift, Tests/TripKitUITests/TKUIRoutingQueryInputViewModelTest.swift, TripKit.xcodeproj/project.pbxproj
Routing results:
- Adjust title and make it one combined accessibility element
rather than a separate one for from+to
- Adjust order to first be title, then close button
- Made the segment view not accessible as the cell already has all
the trip details
Routing query input:
- Adjust order to be close, new title, route, from, swap, to
- Fix initial selection to be on (origin) search bar
- After selecting a location, focus on the other search (if that is
is still missing), or the route button
Also a small style tweak to the query input title view
Addresses RM16010
=> A number of VoiceOver tweaks

Sources/TripKitUI/views/results/TKUISheet.swift
This allows `TKUISheet` caller to perform additional steps after it's dismissed.
=> Dismiss handler for TKUISheet

Sources/TripKit/search/TKPeliasGeocoder.swift, Sources/TripKitUI/helper/RxTripKit/TKGeocoding+Rx.swift
- Pelias gets a hard timeout of 5s as it has a weird behaviour of some requests returning quickly and others taking 10s.
- Bump up stable race cut-off to 1s from 0.25s
- Also: Log Pelias requests and responses
Addresses RM16106
=> Geocoding tweaks

Sources/TripKit/Resources/TripKitModel.xcdatamodeld/7-CleanUp.xcdatamodel/contents, Sources/TripKit/categories/String+NonEmpty.swift, Sources/TripKit/model/API/ServiceAPIModel.swift, Sources/TripKit/model/CoreData/DLSEntry+CoreDataClass.swift, Sources/TripKit/model/CoreData/DLSEntry+CoreDataProperties.swift, Sources/TripKit/model/CoreData/StopVisits+CoreDataClass.swift, Sources/TripKit/model/CoreData/StopVisits+CoreDataProperties.swift, Sources/TripKit/model/TKSegment+TKTripSegment.swift, Sources/TripKit/server/parsing/TKAPIToCoreDataConverter.swift, Sources/TripKitUI/cards/TKUITimetableCard+Content.swift, TripKit.xcodeproj/project.pbxproj
Adds platform information when it was returned on a per-departure
rather than on a per-stop level from `departures.json` or `service.json`.
Also: Fix for String.nonEmpty
---
Example for Leicester, UK, note the "Stand EA" entries:
=> Add departure-level platform information

.github/workflows/swift.yml, Sources/TripKitUI/helper/TKUIModePickerLayoutHelper.swift, Sources/TripKitUI/views/TKUIModePicker.swift
Fixes regression from #123
Also re-adds info on hover (rather than long-tap)
=> Regression fix for mode picker not working on Mac Catalyst

Sources/TripKitUI/view model/TKUITripOverviewViewModel.swift
Noticed I forgot a PR for this. When `trip/update` returned an error, the trip details disappeared. This fixes that.
=> Fixes issue where trip details disappear if real-time update fails

Sources/TripKitUI/cards/TKUIHomeCard.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+CalculateRoutes.swift, Sources/TripKitUI/view model/TKUIRoutingResultsViewModel.swift
Came across this today, while testing the Mi Ride app:
Setting TKUIRoutingResultsCard.config.timePickerConfig.allowsASAP to false and then navigating from home card, to query input, to routing results did not bring up the time picker.
This PR fixes that, by extending the results card constructor that takes a destination, to take an optional origin.
=> Fixes missing prompt for time picker

Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/views/results/TKUIResultsTitleView.swift
Now focuses on from/to of title, with close button at negative swipe.
=> Consistent VoiceOver ordering for routing results screen

Sources/TripKitUI/cards/TKUIHomeCard+Configuration.swift, Sources/TripKitUI/cards/TKUIHomeCard.swift
This is a follow up on https://redmine.buzzhives.com/issues/16538. It was decided that focusing on the origin when query input card is launched should be limit to MI Ride only.
=> Option to set focus on query input search bar

Sources/TripKit/model/API/UserAPIModel.swift
- `firstName` => `givenName`
- `lastName` => `familyName`
Old variants remain, but are deprecated.
=> Rename firstName and lastName

Sources/TripKit/server/TKRouter.swift, Sources/TripKit/server/TKRoutingServer.swift
- Allow planning trips without `regions.json` content if base URL or API key is set
- Add an async variant of `multiFetchTrips`
=> Routing server tweaks

Sources/TripKit/server/TKRouter.swift, Sources/TripKit/server/TKSettings+Config.swift, Sources/TripKit/server/TKTripFetcher.swift, Sources/TripKit/server/TKWaypointRouter.swift, Sources/TripKitUI/helper/RxTripKit/TKDeparturesProvider.swift, Tests/TripKitTests/routing/TKSettingsTest.swift
... rather than always implicitly using what's saved in user defaults
- Adds `TKSettings.Config.userSettings()` and `TKSettings.Config.defaultValues()
- Deprecates `TKSettings.Config()` in favour of `TKSettings.Config.userSettings()`
- Deprecates `TKSettings.config`
- Adds `TKRouter.config` override
=> Allow settings routing configuration parameters explicitly

Sources/TripKit/managers/TKLocationManager.swift, Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard+Errors.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/cards/TKUITripOverviewCard.swift, Sources/TripKitUI/controller/TKUIHomeViewController.swift, Sources/TripKitUI/controller/TKUIRoutingResultsViewController.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel+State.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel.swift, Sources/TripKitUI/views/TKUIModePicker.swift, Tests/TripKitUITests/TKUIGeocoderTest.swift
Disable `TKLocationManager` if no "when is use" description provided in `Info.plist`.
TKUIRoutingQueryInputCard won't include "current location" then.
Also:
- Let `TKUIRoutingQueryInputCard` handle "Route" button by default when
no delegate is provided, pushing the routing results.
- Minor style fix for hover on routing results card.
- Documentation tweaks
=> Don't require access to current location

Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/views/results/TKUIResultsSectionFooterView.swift, Sources/TripKitUI/views/results/TKUIResultsSectionHeaderView.swift
- fixed auto layout issue with trip result header (text overlap or missing text)
- fixed auto layout issue with trip result section (no visual issues but present in the logs)
=> fix constraint issues for result header and footer

Sources/TripKit/helpers/TKUserProfileHelper.swift, Sources/TripKit/model/TKModeInfo.swift, Sources/TripKitUI/view model/TKUINearbyViewModel+Content.swift, Sources/TripKitUI/view model/TKUINearbyViewModel.swift
Added mode picker persistence. 
Added `allModes` reference to `filteredNearby` to determine which modes are disabled
mode distinction is determined via `identifier` and `localImageName` as I wanted to reduce saving too much data to UserDefaults. As I see that the distinction of TKModeInfo is via its variables (Equatable). 
Would be nice if there is a single variable that uniquely identifies the mode since `identifier` seems to be showing a group-type value, and gets every beam / neuron modes alike.
On other note: @nighthawk `identifier` seems to be a group-type value which is good for sorting initially #186 but there seems to be grouping based on location, so that might be an issue. I get now why you mentioned before that this is not a good group identifier.
=> Mode picker persistence

.github/workflows/docs.yml, Scripts/docs.sh, Sources/TripKit/helpers/TKJSONCache.swift, Sources/TripKit/model/CoreData/Trip+CoreDataClass.swift, Sources/TripKit/search/TKAppleGeocoder.swift, Sources/TripKit/search/TKGeocoding.swift, Sources/TripKit/search/TKTripGoGeocoder.swift, Sources/TripKitUI/controller/TKUIAutocompletionViewController.swift, Sources/TripKitUI/helper/RxTripKit/TKGeocoding+Rx.swift, Sources/TripKitUI/view model/TKUIAutocompletionViewModel.swift, Tests/TripKitTests/Data/regions.json, Tests/TripKitTests/parsing/TKRegionManagerTest.swift
- No need to call local search with empty string
- Don't cancel and re-trigger search while map is in "following" mode
- Cancel requests when search aborted before search has completed, implemented by TKAppleGeocoder and TKTripGoGeocoder
- Fix retain cycle in TKUIAutocompletionVC
=> Tweaks of autocompletion behaviour

Sources/TripKitUI/helper/RxTripKit/TKRealTimeHelper.swift, Sources/TripKitUI/view model/TKUITripModeByModeViewModel.swift
Previously, this would not fire with `.updated` if the trip got updated via someone else updating the trip in between.
=> Fix `TKRealTimeHelper.streamRealTime` to also pass on previous updates, too

Sources/TripKit/managers/TKGeoMonitorManager.swift
We can simplify `TKGeoMonitorManager` by using the geofences and messages as provided by the backend. That simplifies the manager quite a bit. Please review.
=> Simplify TKGeoMonitorManager by using geofences from API

Sources/TripKit/server/TKWaypointRouter.swift, Sources/TripKit/vendor/ASPolygonKit/Polygon.swift, Sources/TripKitUI/cards/TKUITripMapManager.swift, Sources/TripKitUI/cards/TKUITripOverviewCard+Configuration.swift, Sources/TripKitUI/cards/TKUITripOverviewCard.swift, Sources/TripKitUI/view model/TKUITripOverviewViewModel.swift
Also adds `TKWaypointRouter.fetchTrip(addingStopOver:to:)`
(Not yet to be merged, should be opt-in for TKUITripOverviewCard and indicate progress)
=> Example for how to add a stop over to trip by long-tapping the map

Sources/TripKitUI/helper/RxTripKit/TKUIResultsFetcher.swift
Let's you overwrite modes for a request made using `TKUIResultsFetcher`.
=> Allow setting `TKUIResultsFetcher.modeReplacementHandler`

Sources/TripKit/helpers/TKRegionOverlayHelper.swift, Sources/TripKit/model/CoreData/Shape+CoreDataClass.swift, Sources/TripKit/model/TKSegment.swift, Sources/TripKit/vendor/ASPolygonKit/Polygon+GeoJSON.swift, Sources/TripKit/vendor/ASPolygonKit/Polygon.swift, Sources/TripKitUI/cards/TKUIMapManager+Tiles.swift, Sources/TripKitUI/cards/TKUIMapManager.swift, Sources/TripKitUI/cards/TKUIServiceMapManager.swift, Sources/TripKitUI/cards/TKUITripMapManager.swift, Sources/TripKitUI/cards/TKUITripModeByModeCard.swift, Sources/TripKitUI/cards/TKUITripOverviewCard.swift, Sources/TripKitUI/helper/Categories/UIImageView+AsAccessoryImage.swift, Sources/TripKitUI/helper/RxTripKit/TKRealTimeHelper.swift, Sources/TripKitUI/helper/TKUIMapManagerHelper.swift, Sources/TripKitUI/view model/TKUIServiceViewModel+MapContent.swift, Sources/TripKitUI/view model/TKUIServiceViewModel.swift, Sources/TripKitUI/views/TKUIPolylineRenderer.swift, Sources/TripKitUI/views/map annotations/MKAnnotationView+Selectable.swift, Sources/TripKitUI/views/map annotations/TKUIAnnotationViewBuilder.swift, Sources/TripKitUI/views/map annotations/TKUIAnnotations+TripKit.swift, Sources/TripKitUI/views/map annotations/TKUIAnnotations.swift, Sources/TripKitUI/views/map annotations/TKUICircleAnnotationView.swift, Sources/TripKitUI/views/map annotations/TKUISemaphoreView.swift, TripKit.xcodeproj/project.pbxproj, TripKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Now shows semaphores only for the selected leg.
Also:
- Improve selection of stops from TKUIServiceCard
- Fix display of real-time indicator in semaphore
- Fix tile attribution view sticking around
- Fix some real-time updates not reflected on the map
- Fixes issue where template hash code is temporarily lost due to real-time updates, which messes with various things.
- Address some warnings and add some comments
- Don't allow tapping hidden map annotations (by disabling them)
- Minor refactoring
=> Reviewed style of the mode-by-mode map

Sources/TripKit/Resources/de.lproj/TripKit.strings, Sources/TripKit/Resources/es.lproj/TripKit.strings, Sources/TripKit/core/Loc+TripKitUI.swift, Sources/TripKit/managers/TKCalendarManager+Autocompleting.swift, Sources/TripKit/managers/TKContactsManager+TKAutocompleting.swift, Sources/TripKit/search/TKGeocoding.swift, Sources/TripKit/search/TKRegionAutocompleter.swift, Sources/TripKitUI/cards/TKUILocationMapManager.swift, Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift, Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift, Sources/TripKitUI/cards/TKUIRoutingResultsMapManager.swift, Sources/TripKitUI/helper/RxTripKit/NSManagedObjectContext+Rx.swift, Sources/TripKitUI/helper/TKUICustomization.swift, Sources/TripKitUI/view model/TKUIAutocompletionViewModel.swift, Sources/TripKitUI/view model/TKUIHomeViewModel+Search.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel+State.swift, Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel.swift, Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+CalculateRoutes.swift, Sources/TripKitUI/view model/TKUIRoutingResultsViewModel.swift, Tests/TripKitUITests/TKUIRoutingQueryInputViewModelTest.swift, TripKit.xcodeproj/project.pbxproj
- Add customisation to TripKitUI to allow adding a generic (i) button (`TKAutocompleting` providers can opt out of it)
- Push location details card when tapping the button
- Use that in the search on home card
- Use that in the search from routing query input card => This should then show "Start here" or "End here"
- Add (i) button callout to map pins when dropping in routing results card
- Auto-select map pin when dropping one on home card or routing results card
=> Adds TKUICustomization.shared.locationInfoTapHandler

Sources/TripKit/managers/TKOneOffLocationManager.swift, TripKit.xcodeproj/project.pbxproj
Adds a simpler location manager, useful for just getting the current location.
It's a simpler version of `TKLocationManager` that's based on some of the code in `GeoMonitor`. I first tried using `TKLocationManager` but it's not working well for just fetching a single location and then forgetting about the rest.
=> Adds `TKOneOffLocationManager`

Sources/TripKitUI/controller/TKUIHomeCardCustomizationViewController.swift, Sources/TripKitUI/view model/TKUIHomeCardCustomizationViewModel.swift
The option existed but was never used. The `enabled` toggle will now be faded out to indicate that you can't hide those sections.
=> Fix for making the home card respect the customiser's `canBeHidden`

Sources/TripKit/core/Loc+TripKitUI.swift, Sources/TripKit/model/CoreData/Trip+CoreDataClass.swift, Sources/TripKit/server/TKSettings.swift, Sources/TripKitUI/views/trip overview/TKUINotificationView.swift
- Adds `TKSettings.notificationTimeToLeaveHeadway` to customise the "your trip is about to start" timing, instead of fixed 15 mins
- Addresses a missing translation
=> 19927 custom headway

Sources/TripKitUI/cards/TKUIMapManager.swift, Sources/TripKitUI/cards/TKUITripModeByModeCard.swift, Sources/TripKitUI/cards/TKUITripOverviewCard.swift
Just keep it on mode-by-mode card. It's distracting and not useful on the overview card.
Resolves https://redmine.buzzhives.com/issues/19584
=> Disable polyline selection on trip overview card

.github/workflows/docs-dryrun.yml, .github/workflows/docs.yml, .github/workflows/swift.yml, Examples/MiniMap/MiniMap/AppDelegate.swift, Examples/MiniMap/MiniMap/ViewController.swift, Package.swift, Sources/TripKit/core/TKCrossPlatform.swift, Sources/TripKit/managers/TKCalendarManager.swift, Sources/TripKit/vendor/ASPolygonKit/QuickLookable.swift, Sources/TripKitUI/views/trip overview/TKUIPathChartView.swift
The old `requestAccess(to: .event)` immediately errors.
=> Re-instate support for asking for calendar access on iOS 17

Sources/TripKit/server/TKServer+ImageUpload.swift, Sources/TripKit/server/parsing/TKRoutingParser.swift
- `TKServer.upload` is now async and passes on headers and tweaks logging
- Parsing trips is more robust by skipping invalid trips from backend (due to missing templates)
=> Robustness and refactoring

Sources/TripKitUI/views/results/TKUIResultsAccessoryView.xib
fixes squashed / compressed transport button for results accessory view
=> fix for squashed transport button in results accessory
