- TripKitUI/core/TransportKitUI/SGTripSegmentsView.h
- TripKitUI/core/TransportKitUI/SGTripSegmentsView.m
- TripKitUI/core/TransportKitUI/SGTripSummaryCell.h
- TripKitUI/core/TransportKitUI/SGTripSummaryCell.m
- TripKitUI/core/TransportKitUI/SGTripSummaryCell.swift
This PR addresses DuyCT's comment in this issue: https://redmine.buzzhives.com/issues/9422
> Provided an option to produce low-constrast trip segment view

- TripKit.xcodeproj/project.pbxproj
- TripKit/AddOns/Bookings/AccountKit/Model/Server/AMKCommunicator.m
- TripKit/AddOns/Bookings/BookingKit/Controller/BPKBookingViewController.m
- TripKit/AddOns/Bookings/BookingKit/Model/BPKServerUtil.m
- TripKit/AddOns/Bookings/TKBookingTransitioner.swift
- TripKit/AddOns/Bookings/TKLinkedAccountHelper.swift
- TripKit/AddOns/Share/TKShareURLProvider.swift
- TripKit/Classes/core/CoreKit+Rx/SVKServer+Rx.swift
- TripKit/Classes/core/ServerKit/SVKServer.h
- TripKit/Classes/core/ServerKit/SVKServer.m
- TripKit/Classes/core/ServerKit/SVKServer.swift
- TripKit/Classes/model/API/BaseAPIModels.swift
- TripKit/Classes/model/API/VehicleAPIModel.swift
- TripKit/Classes/server/TKBuzzRouter.m
- TripKit/Classes/server/TKDeparturesProvider.swift
- TripKit/Classes/server/TKLocationRealTime.swift
- TripKit/Classes/server/TKQuickBookingHelper.swift
- TripKit/Classes/server/TKReporter.swift
Fast-tracking some changes from #41
> Cherry-picking some changes from feature/agendaOnline

- Package.swift
- Sources/TripKitUI/cards/TKUIComposingMapManager.swift
- Sources/TripKitUI/cards/TKUIMapManager+Tiles.swift
- Sources/TripKitUI/cards/TKUIMapManager.swift
- Sources/TripKitUI/cards/TKUINearbyMapManager.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsMapManager.swift
- Sources/TripKitUI/cards/TKUIServiceMapManager.swift
- Sources/TripKitUI/cards/TKUITripMapManager.swift
- Sources/TripKitUI/views/trip overview/TKUIAttributionView.swift
- TripKit.xcodeproj/project.pbxproj
- TripKitUI.podspec
Depends on https://github.com/skedgo/TGCardViewController/pull/2
> Update for safe area of TGCardVC

- Sources/TripKit/model/CoreData/Trip+CoreDataProperties.swift
- Sources/TripKitUI/helper/Trip+Titles.swift
- Sources/TripKitUI/view model/TKUITripOverviewViewModel.swift
The trip is in the process of being updated, and somehow it's losing
these properties. Haven't been able to reproduce, but this avoids
this particular crash.
> Fix crash happening from KVO

- Sources/TripKitUI/cards/TKUIHomeCard+Customizer.swift
- Sources/TripKitUI/cards/TKUIHomeCard.swift
- Sources/TripKitUI/cards/TKUIMapManager+Tiles.swift
- Sources/TripKitUI/cards/TKUIMapManager.swift
- Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/cards/TKUITimetableCard.swift
- Sources/TripKitUI/controller/TKUIHomeCardCustomizationViewController.swift
- Sources/TripKitUI/view model/TKUIHomeViewModel+Component.swift
- Sources/TripKitUI/view model/TKUIHomeViewModel+Next.swift
- Sources/TripKitUI/views/TKUIExtendedActionView.swift
- Sources/TripKitUI/views/TKUIModePicker.swift
- Sources/TripKitUI/views/alerts/TKUIAlertCell.swift
- Sources/TripKitUI/views/results/TKUIProgressCell.swift
- Sources/TripKitUI/views/results/TKUIResultsAccessoryView.swift
- Sources/TripKitUI/views/routing input/TKUIRoutingQueryInputTitleView.swift
- Sources/TripKitUI/views/timetable/TKUIServiceHeaderView.swift
- Sources/TripKitUI/views/trip overview/TKUISegmentAlertCell.swift
- TripKit.xcodeproj/project.pbxproj
Point to Kingfisher 7.0 (temporarily the beta), to build with Xcode 13
> TripKitUI now requires iOS 13

- .github/workflows/swift.yml
- Sources/TripKitUI/cards/TKUITableCard.swift
Symptom, see there's an additional white space below the last cell in a section, as well as a separator between the first cell and the section header. I noticed that this seems to happen with plain table view style.
The fix was done in `TKUITableCard` so all its subclasses receives this behaviour.
> iOS 15 has default padding above section header

- Sources/TripKit/server/TKReporter.swift
- Sources/TripKitUI/cards/TKUIEventCallback.swift
- Sources/TripKitUI/cards/TKUITableCard.swift
- Sources/TripKitUI/cards/TKUITripModeByModeCard.swift
- Sources/TripKitUI/cards/TKUITripOverviewCard.swift
- Sources/TripKitUI/helper/RxTripKit/TKReporter+Rx.swift
- TripKit.xcodeproj/project.pbxproj
Also pass a `DisposeBag` to `.tripSelected` to make it easier to abort reporting planned trips.
> Add TKReporter+Rx

- Sources/TripKitUI/views/TKUICardActionsView.swift
- Sources/TripKitUI/views/TKUIExtendedActionView.swift
- Sources/TripKitUI/views/TKUIExtendedActionView.xib
- Sources/TripKitUI/views/TKUIModePicker.swift
- Don't read out invisible buttons in mode picker (RM15708)
- Fix accessibility of extended action button (RM15707)
> VoiceOver tweaks

- Sources/TripKitUI/cards/TKUIMapManager.swift
This addresses https://redmine.buzzhives.com/issues/15942
> Remove cyclosm attribution on mapman clear up

- Sources/TripKit/categories/NSNumber+Formatter.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/views/TKUITripSegmentsView.swift
- Sources/TripKitUI/views/results/TKUIResultsSectionFooterView.swift
- font increases in response to dynamic font changes
- action button obtains priority, so doesn't get squashed
>  tweak routing results cell footer

- Sources/TripKit/core/Loc+TripKit.swift
- Sources/TripKit/core/Loc+TripKitUI.swift
- Sources/TripKit/model/CoreData/TripRequest+CoreDataClass.swift
- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard+Configuration.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel+State.swift
- Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+CalculateRoutes.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel.swift
- Sources/TripKitUI/views/results/TKUIResultsTitleView.swift
- Sources/TripKitUI/views/results/TKUISheet.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet+Configuration.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
- TripKit.xcodeproj/project.pbxproj
Redmine: https://redmine.buzzhives.com/issues/15500 + https://redmine.buzzhives.com/issues/15741
> Customising time picker sheet + return trip booking option

- Sources/TripKit/model/TKBookingTypes.swift
This addresses this ticket: https://redmine.buzzhives.com/issues/15994
> Support timezone for booking input

- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+CalculateRoutes.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet+Configuration.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
This is addressing https://redmine.buzzhives.com/issues/15499
> Customizing time type labels

- Sources/TripKit/model/CoreData/SegmentReference+Data.swift
- Sources/TripKit/model/TKSegment.swift
- Sources/TripKitInterApp/TKInterAppCommunicator+ExternalActions.swift
- Sources/TripKitUI/cards/TKUICardAction.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+Content.swift
- Sources/TripKitUI/views/TKUICardActionsView.swift
- Sources/TripKitUI/views/trip overview/TKUISegmentCellHelper.swift
> Add custom accessibility label for bookings

- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/cards/TKUITripModeByModeCard.swift
- Sources/TripKitUI/views/results/TKUISheet.swift
Fixes special case where the time picker is presented after coming from the query input card.
Fixes follow-up issue from RM16010.
> VoiceOver fix when there's an overlay

- Sources/TripKit/server/TKBuzzInfoProvider.swift
- Sources/TripKit/server/TKRealTimeFetcher.swift
> Fix missing real-time information on service card

- Sources/TripKitUI/cards/TKUITimetableCard.swift
This appears to have affected close to 10 devices running ODIN
> Fixed a potential crash when scrolling timetable

- Sources/TripKit/Resources/TripKit.xcassets/Colors/TKLabelSecondary.colorset/Contents.json
- Sources/TripKit/core/Loc+TripKitUI.swift
- Sources/TripKit/model/API/RoutingAPIModel.swift
- Sources/TripKit/model/CoreData/Trip+Flags.swift
- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKit/server/parsing/TKRoutingParser.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/cards/TKUITripModeByModeCard.swift
- Sources/TripKitUI/helper/Trip+Titles.swift
- Sources/TripKitUI/views/map annotations/TKUIAnnotations+TripKit.swift
- Sources/TripKitUI/views/results/TKUITripCell+Formatter.swift
- Sources/TripKitUI/views/results/TKUITripCell.swift
This closes https://redmine.buzzhives.com/issues/16205
> Support new flag: hideExactTimes

- Sources/TripKit/model/CoreData/Trip+CoreDataClass.swift
> Hide exact times also in accessibility label

- Sources/TripKitUI/views/results/TKUISheet.swift
This happens with VoiceOver when double tapping the time picker,
which then brings up the software keyboard to enter a time.
> Fixes issue where the time picker is covered by by the keyboard

- Sources/TripKitUI/helper/RxTripKit/TKServer+Rx.swift
Alternative implementation for #144, just changing `hit` and not `stream`.
> TKServer.hit can pass on server and decoding errors

- Sources/TripKit/model/CoreData/Trip+CoreDataClass.swift
- Sources/TripKit/model/TKSegment+TKTripSegment.swift
- Sources/TripKitUI/cards/TKUIMapManager.swift
Went through some TripGo crash logs and fixed some rare crashes.
> Robustness

- Examples/MiniMap/MiniMap.xcodeproj/xcshareddata/xcschemes/MiniMap.xcscheme
- Sources/TripKit/server/TKQuickBookingHelper.swift
- Sources/TripKit/server/TKReporter.swift
- Sources/TripKit/server/TKRouter.swift
- Sources/TripKit/server/TKRoutingServer.swift
- Sources/TripKit/server/TKServer+Regions.swift
- Sources/TripKit/server/TKServer.swift
- Sources/TripKit/server/TKTripFetcher.swift
- Sources/TripKit/sharing/TKShareURLProvider.swift
- Sources/TripKitObjc/TKServer.m
- Sources/TripKitObjc/include/TripKitObjc/TKServer.h
- Sources/TripKitUI/helper/RxTripKit/TKServer+Rx.swift
- Sources/TripKitUI/helper/RxTripKit/TKUIResultsFetcher.swift
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKit-iOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKit-macOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKitInterApp-iOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKitUI-iOS.xcscheme
This means several class methods from TKServer have become instance methods.
> Allow specifying API Key per `TKServer`/`TKRoutingServer` instance

- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKitUI/cards/TKUIHomeCard.swift
This closes https://redmine.buzzhives.com/issues/16532
> Booking action supporting "plan next"

- Sources/TripKitUI/cards/TKUIHomeCard.swift
This closes https://redmine.buzzhives.com/issues/16538
> Query input starts in origin mode

- Sources/TripKit/server/TKRouter.swift
- Sources/TripKitObjc/TKConfig.m
- Sources/TripKitObjc/TKStyleManager.m
- Sources/TripKitObjc/include/TripKitObjc/TKConfig.h
- Sources/TripKitObjc/include/TripKitObjc/TKStyleManager.h
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
- Fix accessing TripRequest from wrong thread during routing
- Fix calling back on wrong thread when showing advisory
- Fix inconsistency in date after pressing "Now" button
Also:
- Clean-up unused methods and configurations
> Robustness fixes

- Sources/TripKitObjc/TKTransportModes.m
... which was switched to `ps_drt` a while ago
> Update mode identifier for DRT

- LICENSE
- README.md
- Sources/TripKitObjc/TKServer.m
> Silence a warning that can be addressed later

- Sources/TripKit/categories/NSManagedObject+Safely.swift
- Sources/TripKit/server/TKServer+Image.swift
- Sources/TripKit/sharing/TKShareURLProvider.swift
- Tests/TripKitUITests/TKUIGeocoderTest.swift
- TripKit.xcodeproj/project.pbxproj
- Add internal `tk_safeRead` and `tk_safeWrite` helpers, use them in TKShareURLProvider
- Also: Log TKServer+Image server requests
> Threading fixes

- Sources/TripKit/model/TKBookingTypes.swift
Add "NUMBER" input type, with optional min and max
> Bookings: Add number input

- Scripts/docs/source/CNAME
Otherwise, it keeps breaking after each deploy
> Add CNAME to repo

- Sources/TripKit/model/TKSegment.swift
- Sources/TripKitUI/cards/TKUICardAction.swift
- Sources/TripKitUI/cards/TKUICardActionStyle.swift
- Sources/TripKitUI/cards/TKUIStartTripAction.swift
- Sources/TripKitUI/views/TKUICardActionsView.swift
- Sources/TripKitUI/views/TKUICompactActionCell.swift
- Sources/TripKitUI/views/TKUIExtendedActionView.swift
Also:
- Add helper for easier dynamic action generation
- Update, enhance docs
> New "destructive" action type

- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/views/results/TKUIResultsSectionFooterView.swift
- Sources/TripKitUI/views/results/TKUIResultsSectionHeaderView.swift
Same as #181, but applied to `main` branch.
* fix constraint issues for result header and footer
* add static height delegate methods for header and footer
> fix constraint issues for result header and footer (#181)

- Sources/TripKit/server/TKRouter.swift
Addresses https://redmine.buzzhives.com/issues/17485
> Opt into failing on any error for multi-fetch requests

- Sources/TripKit/model/TKLocationTypes.swift
- Sources/TripKit/server/TKWaypointRouter.swift
Refactor and review TKWaypointRouter, adding explicit Swift model for data input rather than using `[String: Any]`.
Backend API documentation update is here: https://github.com/skedgo/tripgo-api/pull/224
> TKWaypointRouter now send shared vehicle ID

- Sources/TripKitUI/view model/TKUINearbyViewModel.swift
Added mode picker alphabetical sorting.
> Mode Picker sorting

- Sources/TripKit/helpers/classification/TKMetricClassifier.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard+Configuration.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+Content.swift
Set via `TKUIRoutingResultsCard.config.tripBadgesToShow`
> Adds simple setting to determine which badges to show on trip groups

- Sources/TripKit/categories/NSNumber+Formatter.swift
- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKit/server/TKQuickBookingHelper.swift
- Sources/TripKit/server/TKServer.swift
- Sources/TripKit/server/parsing/TKRoutingParser.swift
- Sources/TripKitUI/helper/RxTripKit/TKServer+Rx.swift
- Sources/TripKitUI/views/segment cards/TKUISegmentTitleView+TKSegment.swift
> Update data model

- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKit/server/TKServer.swift
- Sources/TripKitObjc/TKServer.m
- Sources/TripKitObjc/include/TripKitObjc/TKServer.h
- Sources/TripKitUI/cards/TKUIStartTripAction.swift
- Sources/TripKitUI/cards/TKUITripModeByModeCard.swift
- Sources/TripKitUI/helper/Categories/TKSegment+Zoom.swift
- Sources/TripKitUI/views/segment cards/TKUISegmentMode.swift
Also: 
- Location's address is optional
- Allow sending custom headers to SkedGo URLs
- And async/await methods from `main` branch
> TicketPurchase data model

- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKit/server/TKServer.swift
- Sources/TripKitObjc/TKServer.m
- Sources/TripKitObjc/include/TripKitObjc/TKServer.h
- Sources/TripKitUI/cards/TKUIStartTripAction.swift
- Sources/TripKitUI/cards/TKUITripModeByModeCard.swift
- Sources/TripKitUI/helper/Categories/TKSegment+Zoom.swift
- Sources/TripKitUI/views/segment cards/TKUISegmentMode.swift
> Ticket purchases

- README.md
- TripKit.podspec
- TripKitUI.podspec
> README and podspec updates

- Sources/TripKit/helpers/classification/TKMetricClassifier.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard+Configuration.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+Content.swift
Set via `TKUIRoutingResultsCard.config.tripBadgesToShow`
> Adds setting to determine which badges to show on trip groups

- .github/workflows/docs-dryrun.yml
- .github/workflows/docs.yml
- Examples/TripKitUIExample/ViewController.swift
- Sources/TripKit/managers/TKRegionManager.swift
- Sources/TripKit/model/API/AlertAPIModels.swift
- Sources/TripKit/model/API/RouteAPIModel.swift
- Sources/TripKit/model/CoreData/StopLocation+CoreDataClass.swift
- Sources/TripKit/model/CoreData/StopLocation.swift
- Sources/TripKit/server/TKBuzzInfoProvider+Routes.swift
- Sources/TripKit/server/TKBuzzInfoProvider.swift
- Sources/TripKit/server/TKRealTimeFetcher.swift
- Sources/TripKit/server/TKRegion.swift
- Sources/TripKit/server/TKServer.swift
- Sources/TripKit/server/TKWaypointRouter.swift
- Sources/TripKit/sharing/TKShareHelper.swift
- Sources/TripKit/sharing/categories/StopLocation+Shareable.swift
- Sources/TripKit/sharing/categories/StopVisits+Shareable.swift
- Sources/TripKitUI/helper/RxTripKit/TKAvailabilityFetcher.swift
- Sources/TripKitUI/helper/RxTripKit/TKBuzzInfoProvider+Rx.swift
- Sources/TripKitUI/helper/RxTripKit/TKDeparturesProvider.swift
- Sources/TripKitUI/helper/RxTripKit/TKLocationRealTime.swift
- Sources/TripKitUI/view model/TKUISectionedAlertViewModel.swift
- Sources/TripKitUI/views/alerts/TKUIGroupedAlertCell.swift
Along with an example in TripKitUIExample how to use it
Also: `region.name` has been deprecated in favour of `region.code`
> Adds TKBuzzInfoProvider.fetchRouteDetails

- Examples/TripKitUIExample/Base.lproj/Main.storyboard
- Examples/TripKitUIExample/ExampleCustomizer.swift
- Examples/TripKitUIExample/ViewController.swift
- Sources/TripKitUI/cards/TKUIHomeCard.swift
- Sources/TripKitUI/cards/TKUISimpleHomeMapManager.swift
- Sources/TripKitUI/view model/TKUINearbyViewModel.swift
- TripKit.xcodeproj/project.pbxproj
- Passes current map region to autocompletion and components
- Allow long-tap to drop a pin to route there
> Adds `TKUISimpleHomeMapManager` as a default home map manager

- Sources/TripKitUI/cards/TKUIStartTripAction.swift
- add suport for specified labels for voice over use
> add support for labels for voice over

- Examples/TripKitUIExample/ViewController.swift
- Sources/TripKit/model/API/AlertAPIModels.swift
- Sources/TripKit/server/TKDeparturesProvider.swift
- Sources/TripKitUI/cards/TKUIMapManager.swift
- Sources/TripKitUI/cards/TKUINearbyMapManager.swift
- Tests/TripKitTests/Data/routes-sf.json
- Tests/TripKitTests/parsing/TKBuzzInfoProviderTest.swift
- TripKit.xcodeproj/project.pbxproj
- Allow setting a default location on `TKUINearbyMapManager`
- Allow creating a `TKDeparturesProvider.Filter`
- Make a more alert properties public
- Update example
> Tweaks & Fixes

- Examples/MiniMap/MiniMap.xcodeproj/xcshareddata/xcschemes/MiniMap.xcscheme
- Sources/TripKit/server/TKSettings+Config.swift
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKit-Package.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKit-iOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKit-macOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKitInterApp-iOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKitUI-iOS.xcscheme
- TripKit.xcodeproj/xcshareddata/xcschemes/TripKitUIExample.xcscheme
> Compile fix

- Package.resolved
- Package.swift
- Sources/TripKitUI/cards/TKUITripOverviewCard.swift
- Sources/TripKitUI/managers/TKUITripMonitorManager.swift
- Sources/TripKitUI/view model/TKUITripOverviewViewModel.swift
- TripKit.xcodeproj/project.pbxproj
- TripKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
(Get-off alerts remain iOS 14+)
> Re-instate compatibility with iOS 13

- Sources/TripKit/server/TKWaypointRouter.swift
Crash was reported here: https://redmine.buzzhives.com/issues/18747
> Fixes which callback queue to use from waypoint router

- Sources/TripKit/server/TKRouter.swift
(Which lead to a Swift continuation misuse error.)
> Fix missing callback on some errors

- Sources/TripKit/UIKit/UIColor+TripKit.swift
- Sources/TripKit/UIKit/UIColor+TripKitDefault.swift
- Sources/TripKitUI/views/trip overview/TKUINotificationView.swift
- Sources/TripKitUI/views/trip overview/TKUINotificationView.xib
programmatically set the colors for TKUINotificationView to enable dark mode colors, **custom color selection in xib** only sets the current color that it was set and does not adapt to dark mode.
> Fix TKUINotificationView dark mode color usage

- Sources/TripKit/model/CoreData/Shape+Data.swift
See https://github.com/skedgo/tripgo-api/pull/239
> Adds support for new safety-related road tags

- Sources/TripKit/model/TKBookingTypes.swift
add support for new confirmation message api handling
> Backend message confirmation support

- Sources/TripKit/model/API/RoutingAPIModel.swift
- Sources/TripKit/model/API/ServiceAPIModel.swift
See https://github.com/skedgo/tripgo-api/pull/242
> Parse new routeID field

- Sources/TripKit/Resources/de.lproj/TripKit.strings
- Sources/TripKit/core/Loc+TripKitUI.swift
- Sources/TripKit/helpers/classification/TKMetricClassifier.swift
- Healthiest => Most Active
- Only badge if exceeding a minimum absolute threshold for some metrics
> Tweak badges

- Sources/TripKit/model/CoreData/Shape+CoreDataClass.swift
- Sources/TripKit/model/CoreData/Shape+Data.swift
- Sources/TripKit/model/TKSegment.swift
- Sources/TripKitUI/view model/TKUITripOverviewViewModel+Content.swift
- Sources/TripKitUI/views/trip overview/TKSegment+AccessoryViews.swift
- Sources/TripKitUI/views/trip overview/TKUIPathChartView+TKSegment.swift
- Sources/TripKitUI/views/trip overview/TKUIPathChartView.swift
- Sources/TripKitUI/views/trip overview/TKUIPathChartable.swift
- Sources/TripKitUI/views/trip overview/TKUIPathFriendlinessView.swift
- Sources/TripKitUI/views/trip overview/TKUISegmentMovingCell.swift
- TripKit.xcodeproj/project.pbxproj
Replaces TKUIPathFriendlinessView and also supports road tags
> Add new TKUIPathChartView, based on Swift Charts

- Sources/TripKit/model/API/RoutingAPIModel.swift
- Sources/TripKit/model/CoreData/SegmentTemplate+Data.swift
- Sources/TripKit/model/TKBookingTypes.swift
- Sources/TripKit/model/TKSegment.swift
- Sources/TripKit/server/TKQuickBookingHelper.swift
- Sources/TripKit/server/parsing/SegmentTemplate+Parsing.swift
modify TKQuickBookingHelper and TKBookingTypes for rider filtering in Quick Booking
> Token Transit 2

- Sources/TripKitUI/helper/TKUIMapManagerHelper.swift
Resolves https://redmine.buzzhives.com/issues/19583
> Show missing stop name in trip overview card on stops along the way

- Sources/TripKitUI/cards/TKUIHomeCard.swift
- Sources/TripKitUI/cards/TKUIRoutingQueryInputCard.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsMapManager.swift
- Sources/TripKitUI/cards/TKUITableCard.swift
- Sources/TripKitUI/cards/TKUITimetableCard.swift
- Sources/TripKitUI/cards/TKUITripMapManager.swift
- Sources/TripKitUI/cards/TKUITripOverviewCard.swift
- Sources/TripKitUI/controller/TKUIAutocompletionViewController.swift
- Sources/TripKitUI/helper/RxHelpers.swift
- Sources/TripKitUI/helper/TKUIInteractionResult.swift
- Sources/TripKitUI/view model/TKUIAutocompletionViewModel.swift
- Sources/TripKitUI/view model/TKUIHomeCardCustomizationViewModel.swift
- Sources/TripKitUI/view model/TKUIHomeViewModel+Next.swift
- Sources/TripKitUI/view model/TKUINearbyViewModel.swift
- Sources/TripKitUI/view model/TKUIRoutingQueryInputViewModel.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel.swift
- Sources/TripKitUI/view model/TKUITripOverviewViewModel.swift
- Sources/TripKitUI/views/TKUIModePicker.swift
- Sources/TripKitUI/views/results/TKUIResultsTitleView.swift
- Sources/TripKitUI/views/results/TKUIRoutingQueryInputTitleView.swift
- TripKit.xcodeproj/project.pbxproj
- Add and use `.asAssertingSignal()`
- Add `.with()` and `TKUITriggerResult` (not yet used)
> Refactoring

- Sources/TripKit/model/API/RoutingAPIModel.swift
- Sources/TripKit/model/CoreData/Trip+Data.swift
- Sources/TripKit/server/parsing/TKRoutingParser.swift
- Sources/TripKitUI/cards/TKUICardAction.swift
- Sources/TripKitUI/cards/TKUIRoutingResultsCard.swift
- Sources/TripKitUI/view model/TKUIRoutingResultsViewModel+Content.swift
- Sources/TripKitUI/views/results/TKUIResultsAccessoryView.swift
- Sources/TripKitUI/views/results/TKUIResultsSectionFooterView.swift
Also allow disabling action buttons on routing results screen
> Parse new `availabilityInfo` on trips and show in routing results

- Sources/TripKit/server/TKRouter.swift
- Tests/TripKitTests/parsing/TKRegionManagerTest.swift
added grouping for school bus modes
added unit test for school bus grouping
> group school bus modes request

- Sources/TripKitUI/cards/TKUISegmentDirectionsCard.swift
the hosting card view had the background but not the cell, added background color
> fix background color for segment directions card

- Sources/TripKit/core/Loc.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet+Configuration.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
allow Return Trip date picker to pre-select out of range dates
> Return Trip date picker selection updates 

- Sources/TripKit/core/Loc+TripKit.swift
- add "add location" string to Loc
> Add "Add Location" Loc String

- Sources/TripKit/core/Loc.swift
- Sources/TripKitUI/views/results/TKUIDateTimePickerView.swift
- Sources/TripKitUI/views/results/TKUIDateTimePickerViewController.swift
- Sources/TripKitUI/views/results/TKUIDateTimePickerViewModel.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet+Configuration.swift
- Sources/TripKitUI/views/results/TKUITimePickerSheet.swift
- Sources/TripKitUI/views/results/TKUITimePickerViewController.swift
- TripKit.xcodeproj/project.pbxproj
- add TKUITimePickerViewController
- update TKUITimePickerSheet for ViewController requirements
> Full page time selector

- Sources/TripKit/server/TKServer+ModeImage.swift
- Sources/TripKitUI/helper/Categories/UIImageView+Kingfisher.swift
> Default depo for image URLs is now https://static.skedgo.com/icons/

- Sources/TripKit/server/TKQuickBookingHelper.swift
> Backwards compatibility for #22900

- Sources/TripKit/server/TKTripFetcher.swift
Meaning now version was provided to backend
> Fix query items not being set

- Sources/TripKit/model/TKNamedCoordinate.swift
Also add `TKNamedCoordinate.enableReverseGeocodingAddress`
> Only reverse-geocode each TKNamedCoordinate once

- Sources/TripKit/model/TKNamedCoordinate.swift
> Don't reverse geocode during encoding
